### ISSUE TITLE
关于程序运行的疑问

### ISSUE THREAD

**Issue by qichaotang** [squareRoot3/Target-Guided-Conversation#1]
https://github.com/squareRoot3/Target-Guided-Conversation/blob/master/config/data_config.py#L78
_keywords_path = 'tx_data/test/keywords_vocab.txt' 此行是不是写错了？
按照 readme.txt 里面执行的步骤，此个文件是空的。
还有执行 python prepare_data.py ，产出的 train test valid 文件夹很多是空的

**Comment by qichaotang** [comment]
![image](https://user-images.githubusercontent.com/12878507/60677191-60b01d80-9eb3-11e9-8b1a-0ea0e0fad1c9.png)

**Comment by qichaotang** [comment]
请问下，此个程序是否有问题？

**Comment by squareRoot3** [comment]
程序应该没有问题, 已经有人成功运行了. 执行完 python prepare_data.py, 所有的文件和文件夹都应该是非空的. 
可能的原因第一个是系统, 我只在linux上跑过, 其它系统可能要改几处代码. 第二个是不能直接执行python preprocess/prepare_data.py, 要先cd进文件夹再执行. 可以先看下prepare_data.py的代码来确定下原因.

**Comment by qichaotang** [comment]
感谢您的回复，请问能够提供您处理得出的 tx_data 文件夹，我好对比下，哪里出了问题

**Comment by squareRoot3** [comment]
This link includes processed data and trained agents.
https://stusudaeducn-my.sharepoint.com/personal/jhtang_stu_suda_edu_cn/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fjhtang_stu_suda_edu_cn%2FDocuments%2FTarget-Guided-Conversation%2Ezip&parent=%2Fpersonal%2Fjhtang_stu_suda_edu_cn%2FDocuments&cid=0f3b4912-d592-441a-adcf-8f8c558eb353

**Comment by qichaotang** [comment]
感谢您的提供帮助，但是此个链接好像有问题，打开需要登录，但是登录不了，能否像之前分享数据一样，放在 google drive 上面，也可以方便其他人复现使用

**Comment by qichaotang** [comment]
不成功
很抱歉，在 stusudaeducn-my.sharepoint.com 目录中找不到 tangqichaookok@outlook.com。请稍后再试，同时我们尝试为您自动修复此问题。
这里提供一些建议:

单击此处，以使用其他帐户登录此站点。
这会让您注销目前您已登录的所有其他 Office 365 服务。

如果您正在使用此帐户登录其他站点，且不希望注销，请在浏览器启动站点 的隐私浏览模式(向我展示如何操作)。
如果不起作用，请联系您的支持团队，并告知他们这些技术详细信息:
相关 ID: 5d2bed9e-6082-9000-ddac-e7bfa9d681e6
日期和时间: 2019/7/4 22:08:52
URL: https://stusudaeducn-my.sharepoint.com/personal/jhtang_stu_suda_edu_cn/_layouts/15/onedrive.aspx?id=/personal/jhtang_stu_suda_edu_cn/Documents/Target-Guided-Conversation.zip&parent=/personal/jhtang_stu_suda_edu_cn/Documents&cid=0f3b4912-d592-441a-adcf-8f8c558eb353
用户: tangqichaookok@outlook.com
问题类型: 用户不在目录中。  显示这种错误

**Comment by squareRoot3** [comment]
This link (Onedrive) includes processed data and trained agents, and I will upload one copy to Google Drive Later.

https://stusudaeducn-my.sharepoint.com/:u:/g/personal/jhtang_stu_suda_edu_cn/ETRWfjQskRVAoU3yU722Mj4BnBnr7AHvgxQdZzdp_iz0uQ?e=6VwLWC

**Comment by qichaotang** [comment]
ok，tks

**Comment by squareRoot3** [comment]
Google Drive:
https://drive.google.com/file/d/1cNLPCzOC7MHECaPwOOk0M5rn5T3EIVHQ/view?usp=sharing
